id: I3EE785F4
source: ''
source_file: null
initial_creation_type: input
imported: '2022-08-18T10:28:19.445263'
last_modified: '2022-08-18T10:28:19.445279'
parser: null
source_metadata: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
ocr_word_median_confidence_index: null
ocr_word_mean_confidence_index: null
base: {}
